environment:

  matrix:

    - nodejs_version: "4.0"
    - nodejs_version: "5.0"
    - nodejs_version: "6.0"

platform:

  - x86
  - x64


install:

  - ps: Install-Product node $env:nodejs_version
  - npm config set loglevel warn
  - npm install --silent

test_script:
  
  - node --version
  - npm --version
  - npm test

build: off
