on: push

jobs:
  Lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install Yarn
      run: npm install --global yarn

    - name: Install dependencies
      run: yarn --ignore-engines

    - name: Lint JavaScript files using ESLint
      run: yarn lint
