name: ci

on:
  pull_request:
      branches: [ "*" ]
  push:
      branches: [ master ]
      tags-ignore: [ "*" ]

jobs:

  Lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install dependencies
      run: npx yarn@1.19.1 --ignore-engines

    - name: Lint JavaScript files using ESLint
      run: npm run lint

  Test:

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        node: [ 8.x, 10.x, 12.x ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies
      run: npx yarn@1.19.1 --ignore-engines

    - name: Run tests
      run: npm run test

    - name: Publish code coverage results
      run: npm run coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
