on: push

jobs:
  Test:

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        node: [ 8.x, 10.x, 12.x ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Install Yarn
      run: npm install --global yarn

    - name: Install dependencies
      run: yarn --ignore-engines

    - name: Run tests
      run: yarn test

    - name: Publish code coverage results
      run: yarn coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
